# Generated by Django 5.2 on 2025-05-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_car_alter_carimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='car',
        ),
    ]
