# Generated by Django 5.2 on 2025-04-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
